apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: syncthing-e2e
provisioner: csi.syncthing.io
parameters:
  initialSync: none
volumeBindingMode: WaitForFirstConsumer
reclaimPolicy: Delete
