// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

func (in *SyncthingNode) DeepCopyInto(out *SyncthingNode) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec.Addresses = append([]string(nil), in.Spec.Addresses...)
	if in.Status.LastSeen != nil {
		out.Status.LastSeen = in.Status.LastSeen.DeepCopy()
	}
	out.Status.Conditions = append([]metav1.Condition(nil), in.Status.Conditions...)
}

func (in *SyncthingNode) DeepCopy() *SyncthingNode {
	if in == nil {
		return nil
	}
	out := new(SyncthingNode)
	in.DeepCopyInto(out)
	return out
}

func (in *SyncthingNode) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *SyncthingNodeList) DeepCopyInto(out *SyncthingNodeList) {
	*out = *in
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		out.Items = make([]SyncthingNode, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *SyncthingNodeList) DeepCopy() *SyncthingNodeList {
	if in == nil {
		return nil
	}
	out := new(SyncthingNodeList)
	in.DeepCopyInto(out)
	return out
}

func (in *SyncthingNodeList) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *SyncthingVolume) DeepCopyInto(out *SyncthingVolume) {
	*out = *in
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec.DesiredReplicas = append([]DesiredReplica(nil), in.Spec.DesiredReplicas...)
	if in.Spec.Retention != nil {
		r := *in.Spec.Retention
		out.Spec.Retention = &r
	}
	if in.Status.Replicas != nil {
		out.Status.Replicas = make([]ReplicaStatus, len(in.Status.Replicas))
		for i := range in.Status.Replicas {
			out.Status.Replicas[i] = in.Status.Replicas[i]
			if in.Status.Replicas[i].LastTransitionTime != nil {
				out.Status.Replicas[i].LastTransitionTime = in.Status.Replicas[i].LastTransitionTime.DeepCopy()
			}
		}
	}
	out.Status.Conditions = append([]metav1.Condition(nil), in.Status.Conditions...)
}

func (in *SyncthingVolume) DeepCopy() *SyncthingVolume {
	if in == nil {
		return nil
	}
	out := new(SyncthingVolume)
	in.DeepCopyInto(out)
	return out
}

func (in *SyncthingVolume) DeepCopyObject() runtime.Object { return in.DeepCopy() }

func (in *SyncthingVolumeList) DeepCopyInto(out *SyncthingVolumeList) {
	*out = *in
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		out.Items = make([]SyncthingVolume, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}

func (in *SyncthingVolumeList) DeepCopy() *SyncthingVolumeList {
	if in == nil {
		return nil
	}
	out := new(SyncthingVolumeList)
	in.DeepCopyInto(out)
	return out
}

func (in *SyncthingVolumeList) DeepCopyObject() runtime.Object { return in.DeepCopy() }
