name: CSI sanity

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  csi-sanity:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Check out source
        uses: actions/checkout@v7

      - name: Set up Helm
        uses: azure/setup-helm@v4

      - name: Set up kubectl
        uses: azure/setup-kubectl@v4

      - name: Install Kind
        uses: helm/kind-action@v1.12.0
        with:
          install_only: true
          version: v0.33.0

      - name: Run csi-sanity
        run: make csi-sanity

      - name: Delete Kind cluster
        if: always()
        run: make csi-sanity-clean
